apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-environments
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: bekurin
          repo: preview_env
  template:
    metadata:
      name: 'simple-deployment-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: https://github.com/bekurin/preview_env.git
        targetRevision: '{{head_sha}}'
        path: helm
        helm:
          parameters:
            - name: "image.tag"
              value: '{{head_sha}}'
            - name: "namespace"
              value: 'default'
      project: preview
      destination:
        server: https://kubernetes.default.svc
        namespace: 'default'
